spring:
  application:
    name: hows-weather-api
  profiles:
    active: prod
  cache:
    type: redis
    cache-names: jwtTokenCache,weatherIndices,hourlyWeatherCache,realtimeWeatherCache,dailyWeatherCache
qweather:
  api-host: https://mw3h2nxdcj.re.qweatherapi.com
  project-id: 492FY7QPEH
  key-id: KBPQJ8PK7Y
  private-key-path: classpath:xyz-private.pem
api:
  rate-limit:
    enabled: ${WEATHER_API_RATE_LIMIT_ENABLED:true}
    max-requests-per-day: ${WEATHER_API_MAX_REQUESTS_PER_DAY:100}
    paths: /api/weather/get
