spring:
  application:
    name: hows-weather-api
  profiles:
    active: dev
  cache:
    type: redis
    cache-names: jwtTokenCache,weatherIndices,hourlyWeatherCache,realtimeWeatherCache,dailyWeatherCache
qweather:
  api-host: https://mw3h2nxdcj.re.qweatherapi.com
  project-id: 492FY7QPEH
  key-id: KBPQJ8PK7Y
  private-key-path: classpath:xyz-private.pem
api:
  rate-limit:
    enabled: true
    max-requests-per-day: 10
    paths: /api/weather/get
