name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    # 步骤 1: 检出代码
    - name: Checkout code
      uses: actions/checkout@v4

    # 步骤 2: 设置 QEMU (用于 Buildx 多平台构建支持)
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # 步骤 3: 设置 Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 步骤 4: 登录到 Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }} # 使用访问令牌

    # 步骤 5: 提取 Docker 元数据 (标签和标签)
    - name: Extract metadata (tags, labels) for Docker
      id: meta # 设置步骤 ID 为 'meta'
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/hows-weather-api

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        secrets: |
          QWEATHER_PRIVATE_KEY=${{ secrets.QWEATHER_PRIVATE_KEY }}
